spring:
  application:
    name: discovery-demo
  cloud:
    kubernetes:
      discovery:
        enabled: true   #开启服务发现

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"