server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: provider-service
        uri: ${PROVIDER_ENDPOINT:http://localhost:8081}
        predicates:
        - Path=/api/provider/**
      - id: consumer-service
        uri: ${CONSUMER_ENDPOINT:http://localhost:8082}
        predicates:
        - Path=/api/consumer/**
        filters:
        - StripPrefix=2