server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: provider
        uri: http://provider:8080
        predicates:
        - Path=/api/provider/**
      - id: consumer
        uri: http://customers:8080
        predicates:
        - Path=/api/consumer/**
        filters:
        - StripPrefix=2