server:
  port: 8081
  servlet:
    context-path: /security


spring:
  application:
    name: springboot-security

  profiles:
    active: dev

  thymeleaf:
    mode: HTML
    cache: false

  mvc:
    view:
      prefix: /templates
      suffix: .html