apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate3
spec:
  selector:
    matchLabels:
      app: gate3
  replicas: 2
  template:
    metadata:
      labels:
        app: gate3
    spec:
      containers:
        - name: gate3
          image: registry.cn-hangzhou.aliyuncs.com/muyer-hub/hub1:gateway-3.0
          envFrom:
            - configMapRef:
                name: k8s-config
---
apiVersion: v1
kind: Service
metadata:
  name: gate3
spec:
  selector:
    app: gate3
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
