apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-service
          image: registry.cn-hangzhou.aliyuncs.com/muyer-hub/hub1:gate-1
          envFrom:
            - configMapRef:
                name: petclinic-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
