apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
spec:
  selector:
    matchLabels:
      app: provider
  replicas: 2
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
        - name: provider
          image: registry.cn-hangzhou.aliyuncs.com/muyer-hub/hub1:provider-1.0
          envFrom:
            - configMapRef:
                name: k8s-config
---
apiVersion: v1
kind: Service
metadata:
  name: provider
spec:
  selector:
    app: provider
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
