server:
  port: 8081
  servlet:
    context-path: /thymeleaf/

spring:
  mvc:
    view:
      suffix: /templates
      prefix: .html

  thymeleaf:
    mode: HTML
    cache: false


  ## jpa配置
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl: update
      show-sql: true
  ## 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.129.240:3306/study_demo?useSSL=false&characterEncoding=utf-8
    username: root
    password: yejiang1996

