server:
  port: 8080

spring:
  cloud:
    gateway:
      #通过 predicates拦截 打到对应的uri上
      routes:
      - id: providers-service
        uri: ${PROVIDER_ENDPOINT:http://localhost:8081}
        predicates:
        - Path=/api/provider/**
        filters:
        - StripPrefix=2
      - id: comsumers-service
        uri: ${CUSTOMER_ENDPOINT:http://localhost:8082}
        predicates:
        - Path=/api/comsumer/**
        filters:
        - StripPrefix=2

